name: React CI Workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]
        os: [ubuntu-latest]
        
    runs-on: ${{ matrix-ox }}
    
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use Node. js $< matrix. node-version y
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }} 
          cache: 'npm' 
          
      - name: npm run clean install
        run: npm ci
       
      - name: прm run build, if present
        run: npm run build --if-present

      - name: npm Run tests
        run: npm test
